_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 9ee2a879-a078-49e1-ab1a-07cab636ef5f
name: Drupal
mail: faizan.nasir@innoraft.com
slogan: ''
page:
  403: ''
  404: ''
  front: /index
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
